version: '3.8'

services:
  app:
    build: .
    container_name: flask_graphrag_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./ragtest:/app/ragtest
    environment:
      FLASK_ENV: development
      GRAPHRAG_API_KEY: "YOUR OPEN AI API KEY"

